version = 1

test_patterns = [
  "tests/**",
  "*_tests.py"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"
