version: "3.3"

services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - compose.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    depends_on:
      - db
    env_file:
      - compose.env
    environment:
      - SERVER_HOST=https://127.0.0.1
      - POSTGRES_HOST=db
      # Allow explicit env var override for tests
    build:
      context: .
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  app-db-data:
