version: "3.3"

services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - compose.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    depends_on:
      - db
      - elasticsearch
    env_file:
      - compose.env
    environment:
      - SERVER_HOST=https://127.0.0.1
      - POSTGRES_HOST=db
      - ELASTICSEARCH_HOST=elasticsearch:9200
    build:
      context: .
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"


  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"


volumes:
  app-db-data:
  elasticsearch-data:
