"""Add base models

Revision ID: 7be3cb372b73
Revises:
Create Date: 2023-05-02 18:50:29.056325

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7be3cb372b73"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_videos_published_at"), "videos", ["published_at"], unique=False
    )
    op.create_table(
        "subtitles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subtitles_id"), "subtitles", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subtitles_id"), table_name="subtitles")
    op.drop_table("subtitles")
    op.drop_index(op.f("ix_videos_published_at"), table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
