"""Add category to video model

Revision ID: bef8379aa5b0
Revises: 7be3cb372b73
Create Date: 2023-05-11 19:02:13.473654

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bef8379aa5b0"
down_revision = "7be3cb372b73"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos", sa.Column("category_id", sa.String(length=3), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "category_id")
    # ### end Alembic commands ###
